### PR TITLE
Reduce exiftool calls with metadata object cache.  Enable single exif…

### PR DESCRIPTION
**Pull request by amaleki**
…tool subprocess to elimate spawing exiftool for each image.

### CODE REVIEW

**Comment by amaleki** [comment]
Hi @jmathai 

I'm not having any luck figuring out how to run all tests.  Can you confirm is this the correct command to run elodie tests?

./elodie/tests/run_tests.py -w elodie/tests 

```
----------------------------------------------------------------------
Ran 0 tests in 0.000s
OK
```

**Comment by amaleki** [comment]
Hi @jmathai 

I figure out my issue.  Nosetests doesn't like executables.  

In case someone runs into this in the future the following will output all the files it detects and why it didn't process. 
`nosetests -w elodie/tests/ -vv --collect-only`
To fix run
`chmod -x $(find elodie/tests/ -name '*.py')`

**Comment by jmathai** [comment]
@amaleki 👍 to figuring out how to run the test. Let me know if you have any other questions. I'm just starting to go through the PR.

**Comment by amaleki** [comment]
@jmathai I got the tests to work and found a couple issues.  I've also updated the test scripts to account for setup/teardown of ExifTool() singleton.  I might close this PR and create a new one.  This is my first PR so learning a bit. :)

**Pull request closed without merging**
