### PR TITLE
Add capitalization option for [File] config

### PR DESCRIPTION
**Pull request by muff1nman**

### CODE REVIEW

**Comment by muff1nman** [comment]
Addresses #312

**Comment by jmathai** [comment]
Thanks @muff1nman. Can we add a test for this configuration?

Should be able to copy/paste [this test](https://github.com/jmathai/elodie/blob/master/elodie/tests/filesystem_test.py#L282) for starters and run the following command and updating using whatever you name your test.

```
nosetests elodie/tests/filesystem_test.py:test_get_file_name_custom_with_empty_value
.
----------------------------------------------------------------------
Ran 1 test in 1.705s

OK
```

**Comment by muff1nman** [comment]
Done.

**Comment by jmathai** [comment]
Thanks!

**Pull request merged**
