### PR TITLE
ref #40 Improve code quality

### PR DESCRIPTION
**Pull request by Kraymer**
A first pass on `elodie.py`, pylint score goes up from 2.15/10 to 5.60/10
I did the most obvious edits (most of them superficial) to make the code more compliant with PEP8.

I intend to continue the efforts on others files and more thoroughly, tell me if that's okay with you so i continue to push in this PR.

### CODE REVIEW

**Comment by jmathai** [comment]
@Kraymer This is great :+1: . I've been meaning to do this but I'm new to python and not as familiar with what's proper. I need to read the PEP8 docs :). Please continue to push to this PR. I'll review merge it once I get a chance and you can open another. This will probably be a longer running process.

**Comment by Kraymer** [comment]
> I've been meaning to do this but I'm new to python and not as familiar with what's proper. I need to read the PEP8 docs :)

First thing to do would be to install a [Flake8](https://flake8.readthedocs.org/en/latest/) plugin in your IDE (or a git hook) to warn you when you break the PEP8 :pig:

**Comment by Kraymer** [comment]
Ok I think this PR should be merged before delving into more advanced refactoring.
So I leave it there for elodie.py, and will open another PR for PEP8 cleaning of others files.

**Comment by jmathai** [comment]
@Kraymer I created gh-58 which can be used to check pep8 fixes in against. I've also created a `.pre-commit` file which we can include a pep8 check into once we've addressed all the warnings. For now it just runs the unit tests.

**Comment by jmathai** [comment]
@Kraymer I addressed all the pep8 issues in the non-test files. (`pep8 elodie --exclude=tests`).

**Pull request merged**
