### PR TITLE
Switched to click for argument parsing

### LINKED ISSUE #79: docopt issue when running elodie.py
I've tried running the following command:

```bash
$ ./elodie.py import --source="/Users/arik/Pictures/Incoming" --destination="/Users/arik/Pictures/2016"
```

But got the following error:

```
Traceback (most recent call last):
  File "./elodie.py", line 217, in <module>
    sys.exit(main())
  File "./elodie.py", line 208, in main
    params = docopt(usage())
  File "/usr/local/lib/python2.7/site-packages/docopt.py", line 451, in docopt
    formal_pattern = parse_pattern(formal_usage(usage), options=pot_options)
  File "/usr/local/lib/python2.7/site-packages/docopt.py", line 334, in parse_pattern
    result = parse_expr(tokens, options)
  File "/usr/local/lib/python2.7/site-packages/docopt.py", line 350, in parse_expr
    seq = parse_seq(tokens, options)
  File "/usr/local/lib/python2.7/site-packages/docopt.py", line 360, in parse_seq
    atom = parse_atom(tokens, options)
  File "/usr/local/lib/python2.7/site-packages/docopt.py", line 386, in parse_atom
    result = [Optional(*parse_expr(tokens, options))]
  File "/usr/local/lib/python2.7/site-packages/docopt.py", line 342, in parse_expr
    seq = parse_seq(tokens, options)
  File "/usr/local/lib/python2.7/site-packages/docopt.py", line 360, in parse_seq
    atom = parse_atom(tokens, options)
  File "/usr/local/lib/python2.7/site-packages/docopt.py", line 391, in parse_atom
    return parse_long(tokens, options)
  File "/usr/local/lib/python2.7/site-packages/docopt.py", line 293, in parse_long
    raise tokens.error('%s must not have an argument' % opt.name)
docopt.DocoptLanguageError: --album-from-folder must not have an argument
```

After some debugging I noticed that the value it think it gets is `<a>`, which made me realize that for some reason `--album-from-folder` gets the value of `--album`. Once I changed the `--album` option name to `--zalbum` it worked.

My docopt version is 0.4.0.

Anyone else had this issue?

Personally, I recommend moving from docopt to [click](http://click.pocoo.org/5/) -- far more predictable and stable.

### PR DESCRIPTION
**Pull request by noonat**
Fixes #79. Did some manual testing and everything seems to work in a backwards compatible way.

Example `--help` output:

```
$ python elodie.py --help
Usage: elodie.py [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  import  Import files or directories.
  update  Update files.
```

```
$ python elodie.py import --help
Usage: elodie.py import [OPTIONS] [PATHS]...

  Import files or directories.

Options:
  --destination DIRECTORY  Copy imported files into this directory.
  --source DIRECTORY       Import files from this directory, if specified.
  --file PATH              Import this file, if specified.
  --album-from-folder      Use images' folders as their album names.
  --trash                  After copying files, move the old files to the
                           trash.
  --help                   Show this message and exit.
```

```
$ python elodie.py update --help
Usage: elodie.py update [OPTIONS] FILES...

  Update files.

Options:
  --album TEXT     Update the image album.
  --location TEXT  Update the image location. Location should be the name of a
                   place, like "Las Vegas, NV".
  --time TEXT      Update the image time. Time should be in YYYY-mm-dd
                   hh:ii:ss or YYYY-mm-dd format.
  --title TEXT     Update the image title.
  --help           Show this message and exit.
```

### CODE REVIEW

**Comment by jmathai** [comment]
Ignore the travis failure. Sometimes the precision is off by .000000001.

I was having trouble installing click. Trying to figure that out.

**Comment by noonat** [comment]
Doh, what sort of problem for click?

**Comment by jmathai** [comment]
@noonat I screwed up my python environment when trying to build packages for AWS lambda. Adding a `~/.pydistutils.cfg` with the following was a terrible idea.

```
[install]
prefix= 
```

Thankfully removing that file fixed everything :).

This PR looks good.

**Comment by noonat** [comment]
Oh my, haha! Glad you got it working again!

**Pull request merged**
