### PR TITLE
Modification of patch for #162 and unit test ok

### PR DESCRIPTION
**Pull request by misterpipine**
Unit test validated (ok with the patch/fails without it) and patch also validated with a real import using file paths with non-breaking spaces.

### CODE REVIEW

**Comment by jmathai** [comment]
Looks great. Can you merge or rebase master and resolve conflicts?

**Comment by misterpipine** [comment]
Sure, but how can I do that ?

**Comment by jmathai** [comment]
I did it via the web editor. Assuming my remote is named `jmathai`...

```
git fetch jmathai
git merge jmathai/master
# you'll get conflicts here
# fix the conflicted files, add them, commit and push.
```

**Comment by misterpipine** [comment]
no more conflict but CI fails...

**Comment by jmathai** [comment]
@misterpipine looks like python3 doesn't support `str.unicode()`.

`AttributeError: 'str' object has no attribute 'decode'`

Looks to be sort of a mess with python 2 and 3 compatability. My suggestions are to look into the `codecs` module (see [Codec System](http://lucumr.pocoo.org/2014/1/5/unicode-in-2-and-3/)).

Or have a custom `decode` function that handles it internally in a try/catch. Perhaps in a new utils module that can be imported in `elodie.py`.

Happy to help if you had questions.

**Comment by jmathai** [comment]
I have a python3 environment. If you'd like me to verify a fix and submit a patch to your fork I'll do that.

**Comment by misterpipine** [comment]
I'm not an Python expert but there are major differences between 2 and 3 version and in particular encoding. My understanding was that Elodie was working with version 2. Do I have to switch to version 3 ?

**Comment by jmathai** [comment]
We support both versions. The CI runs in 2 and 3. We should get the tests to pass in 3 before merging.

I'm not sure if you use virtualenv but it's very easy to get a python3 environment up using it.

**Comment by jmathai** [comment]
Looks like the `six` module is the cleanest way to do this. https://pythonhosted.org/six/

**Comment by misterpipine** [comment]
I'll have a look to `six` module to make the CI working.

**Comment by jmathai** [comment]
FWIW I created a PR. https://github.com/misterpipine/elodie/pull/1

**Comment by jmathai** [comment]
The tests pass for my PR. If you wanted to merge it you're welcome to. I would double check that the test fails without the call to `_decode()` in `elodie.py`. https://travis-ci.org/jmathai/elodie/builds/186742124

**Comment by jmathai** [comment]
💯 👍

**Pull request merged**
