### PR TITLE
Add support for a %custom placeholder for more complex folder names than %location or %date provide #279

### PR DESCRIPTION
**Pull request by jmathai**
Addresses #279 

- [x] Add test for fallback support with `%custom` placeholder
- [x] Refactor nested / repeated check for `Directory` in config
- [x] Clean up commented out code
- [x] Rename `filesystem.dynamic_path_append` function
- [x] Add tests for `filesystem.dynamic_path_append` function

### CODE REVIEW

**Comment by QasimK** [comment]
Hi @jmathai,

I took a look at this branch and made some further additions which you can see here: <https://github.com/jmathai/elodie/compare/built-in-custom-directory-placeholder-gh-279...QasimK:built-in-custom-directory-placeholder-gh-279?expand=1>.

- Added test for the fallback to location if album is not present feature: `test_get_folder_path_with_combined_date_album_and_location_fallback`
- Fixed existing tests

I'm a little stuck at this point though. There are two choices for the configuration that would implement the feature:

```
date=%Y-%m-%b
custom=%date %album|%date %city
full_path=%custom
```

and

```
date=%Y-%m-%b
custom=%album|%city
full_path=%date %custom
```

The latter seems like it would be easier to implement, and looks more correct to me. However, it isn't clear that the existing parsing supports doing something like `%date %location`, and I'm not sure if that would break backwards compatibly anywhere. I wanted to get your thoughts before continuing.

I also noticed that the tests use your system's custom `config.ini`, which was a little confusing!

**Comment by jmathai** [comment]
@QasimK thanks for the commit - I've merged it into this PR.

At the moment the parsing does not support splitting on spaces. I agree that makes more sense but perhaps that is something to address in another PR to keep this one simple (the logic which this PR touches is complex as it stands).

**Comment by jmathai** [comment]
I have an odd situation here where the tests pass locally but not in Travis. Haven't seen this before so will debug before merging. There's also 3 items in the PR's checklist which haven't been completed and I need to review those.

**Comment by QasimK** [comment]
Thanks for getting back to this @jmathai! I will consider the splitting on spaces issue separately.

**Comment by ldexterldesign** [comment]
Hey all,

Hope you're well

I see much work has been done since I last visited 😎

I've been playing with the new custom dir/path feature tonight and fallbacks[f] seem very broken - before I give some constructive feedback in the form of use cases, probably in a new issue because all the relevant issues are closed and PRs merged, I just want to check there are no pending issues with fallback support?

Cheers

PS I think there's a typo here[h]:

full_path=%month/%year/%album|%location|*%*"Beats me"

f: https://github.com/jmathai/elodie/issues/279#issuecomment-421542421
h: https://github.com/jmathai/elodie/blame/master/Readme.md#L216

**Comment by jmathai** [comment]
I believe the only issue maybe that fallback folders are only supported on leaf folders (as pointed out in #245). Otherwise there are no known issues with them.

Please open issues if you find any odd or incorrect behavior. If you have multiple which seem unrelated please open separate issues. Thanks!

**Comment by ldexterldesign** [comment]
👆

**Pull request merged**
